# Generated by Django 5.2.8 on 2025-11-27 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet_cryptotransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptotransaction',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='cryptotransaction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='cryptotransaction',
            name='note',
        ),
        migrations.AddField(
            model_name='cryptotransaction',
            name='confirmations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptotransaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('underpaid', 'Underpaid'), ('overpaid', 'Overpaid')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
