# Generated by Django 5.2.8 on 2025-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cryptotransaction_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='qr_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
