# Generated by Django 5.2.8 on 2025-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cryptotransaction_qr_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='address_index',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
