# Generated by Django 5.2.8 on 2026-01-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cryptotransaction_address_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('last_index', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
