# Generated by Django 5.2.8 on 2026-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_walletindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('underpaid', 'Underpaid'), ('overpaid', 'Overpaid'), ('canceled', 'Canceled')], default='pending', max_length=15),
        ),
    ]
