# Generated by Django 5.2.8 on 2026-02-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cardtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtransaction',
            old_name='card_number_masked',
            new_name='card_number',
        ),
    ]
