# Generated by Django 5.2.8 on 2026-02-05 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_card_number_masked_cardtransaction_card_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtransaction',
            name='admin_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='admin_action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_card_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('pending_approval', 'Pending Admin Approval')], default='pending_approval', max_length=20),
        ),
    ]
