# Generated by Django 5.2.8 on 2026-02-09 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_cardtransaction_admin_action_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the proxy', max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('type', models.CharField(choices=[('socks5', 'SOCKS5'), ('http', 'HTTP'), ('https', 'HTTPS')], default='socks5', max_length=10)),
                ('username', models.CharField(blank=True, help_text='Proxy username if required', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='Proxy password if required', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, help_text='Country/Region of proxy', max_length=100, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in milliseconds (optional)', null=True)),
                ('max_uses', models.IntegerField(default=100, help_text='Maximum uses before replacement')),
                ('current_uses', models.IntegerField(default=0, help_text='Number of times used')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
                'ordering': ['-is_active', 'country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OneWinAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='1Win account username', max_length=255, unique=True)),
                ('password', models.CharField(help_text='1Win account password', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Associated phone number', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Account email', max_length=254, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current account balance', max_digits=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=500.0, help_text='Daily deposit/withdrawal limit', max_digits=10)),
                ('total_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount used from this account', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('logged_in', 'Logged In'), ('banned', 'Banned'), ('suspended', 'Suspended'), ('needs_verification', 'Needs Verification'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('account_data', models.JSONField(blank=True, default=dict, help_text='Additional account information (cookies, session data, etc.)')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this account', null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('successful_logins', models.IntegerField(default=0)),
                ('failed_logins', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proxy', models.ForeignKey(blank=True, help_text='Proxy to use for this account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.proxy')),
            ],
            options={
                'verbose_name': '1Win Account',
                'verbose_name_plural': '1Win Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
