# Generated by Django 5.2.8 on 2026-02-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_proxy_onewinaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtransaction',
            name='onewin_account',
            field=models.ForeignKey(blank=True, help_text='1Win account assigned to this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='accounts.onewinaccount'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_id',
            field=models.CharField(blank=True, help_text='Proxy ID from raw string', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='raw_proxy_string',
            field=models.TextField(blank=True, default='no_proxy', help_text='Raw proxy string in format: ID: XXXXXX | 🇳🇱 NL\nHTTP: username:password@ip:port\nSOCKS5: username:password@ip:port'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='name',
            field=models.CharField(default='Proxy', help_text='Descriptive name for the proxy', max_length=100),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, help_text='Proxy password', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, help_text='Proxy username', max_length=100, null=True),
        ),
    ]
