# Generated by Django 5.2.8 on 2026-02-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cardtransaction_onewin_account_proxy_proxy_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWinSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_path', models.CharField(blank=True, help_text='Path to Chrome profile directory for persistent session', max_length=500, null=True)),
                ('session_status', models.CharField(choices=[('no_session', 'No Session'), ('active', 'Active Session'), ('expired', 'Session Expired'), ('needs_login', 'Needs Login'), ('closed', 'Closed')], default='no_session', max_length=20)),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='Additional session metadata (cookies, last URL, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('browser_pid', models.IntegerField(blank=True, null=True)),
                ('debug_port', models.IntegerField(blank=True, null=True)),
                ('account', models.OneToOneField(help_text='1Win account this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='browser_session', to='accounts.onewinaccount')),
            ],
            options={
                'verbose_name': '1Win Browser Session',
                'verbose_name_plural': '1Win Browser Sessions',
            },
        ),
    ]
