# Generated by Django 5.2.8 on 2026-02-12 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_onewinsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255, unique=True)),
                ('user_data_dir', models.CharField(max_length=512)),
                ('remote_debugging_port', models.PositiveIntegerField(blank=True, null=True)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('onewin_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='browser_session', to='accounts.onewinsession')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.proxy')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='accounts_br_is_acti_a4dee2_idx'), models.Index(fields=['profile_name'], name='accounts_br_profile_36884d_idx')],
            },
        ),
    ]
