# Generated by Django 5.2.8 on 2026-02-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_browsersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrowserSession',
        ),
    ]
