# Generated by Django 5.2.8 on 2026-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_browsersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='onewinsession',
            name='session_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
