# Generated by Django 5.2.8 on 2026-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_onewinsession_session_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
