# Generated by Django 5.2.8 on 2026-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_cardtransaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtransaction',
            name='card_type',
            field=models.CharField(default='Visa', max_length=19),
        ),
    ]
