# Generated by Django 5.2.8 on 2026-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_score_match_home_score_match_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
