# Generated by Django 5.2.8 on 2026-01-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_match_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='handicap_value',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_1x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_handicap_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_handicap_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_over_2_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_under_2_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_x2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('home', 'Home Win'), ('draw', 'Draw'), ('away', 'Away Win'), ('1x', 'Double Chance 1X'), ('12', 'Double Chance 12'), ('x2', 'Double Chance X2'), ('over_25', 'Over 2.5 Goals'), ('under_25', 'Under 2.5 Goals'), ('handicap_home', 'Handicap Home'), ('handicap_away', 'Handicap Away')], max_length=20),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='matches.match')),
            ],
            options={
                'unique_together': {('match', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='matches.market')),
            ],
        ),
    ]
