# Generated by Django 5.2.8 on 2026-01-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_handicap_value_match_odds_12_match_odds_1x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='odds_btts_no',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_btts_yes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('home', 'Home Win'), ('draw', 'Draw'), ('away', 'Away Win'), ('1x', 'Double Chance 1X'), ('12', 'Double Chance 12'), ('x2', 'Double Chance X2'), ('over_25', 'Over 2.5 Goals'), ('under_25', 'Under 2.5 Goals'), ('handicap_home', 'Handicap Home'), ('handicap_away', 'Handicap Away'), ('btts_yes', 'Both Teams To Score - Yes'), ('btts_no', 'Both Teams To Score - No')], max_length=20),
        ),
    ]
