# Generated by Django 5.2.8 on 2026-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_odds_btts_no_match_odds_btts_yes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
