# Generated by Django 5.2.8 on 2026-01-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_scraped_at_match_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scraped_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
