# Generated by Django 5.2.8 on 2026-01-21 22:39

import matches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_scraped_at_alter_match_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scraped_at',
            field=models.DateTimeField(blank=True, default=matches.models.get_default_scraped_at, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
