# Generated by Django 5.2.8 on 2026-01-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_expressbet_expressbetselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expressbet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bet',
            name='selected_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='draw_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='first_goal_scorer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='half_time_away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='half_time_home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ah_away_plus_05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ah_away_plus_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ah_home_minus_05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ah_home_minus_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_away_over_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_away_under_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_btts_win_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_btts_win_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_0_0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_0_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_0_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_1_0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_1_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_1_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_2_0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_cs_2_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_dnb_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_dnb_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_even',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_home_over_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_home_under_15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ht_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ht_1x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ht_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ht_draw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ht_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_ht_x2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_aa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_ad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_ah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_da',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_dd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_dh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_hd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_htft_hh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_odd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_over_1_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_over_3_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_under_1_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_under_3_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_win_to_nil_away',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_win_to_nil_home',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('home', 'Home Win'), ('draw', 'Draw'), ('away', 'Away Win'), ('1x', 'Double Chance 1X'), ('12', 'Double Chance 12'), ('x2', 'Double Chance X2'), ('over_2_5', 'Over 2.5 Goals'), ('under_2_5', 'Under 2.5 Goals'), ('handicap_home', 'Handicap Home'), ('handicap_away', 'Handicap Away'), ('btts_yes', 'Both Teams To Score - Yes'), ('btts_no', 'Both Teams To Score - No'), ('over_1_5', 'Over 1.5 Goals'), ('under_1_5', 'Under 1.5 Goals'), ('over_3_5', 'Over 3.5 Goals'), ('under_3_5', 'Under 3.5 Goals'), ('htft_hh', 'Half Time/Full Time - Home/Home'), ('htft_hd', 'Half Time/Full Time - Home/Draw'), ('htft_ha', 'Half Time/Full Time - Home/Away'), ('htft_dh', 'Half Time/Full Time - Draw/Home'), ('htft_dd', 'Half Time/Full Time - Draw/Draw'), ('htft_da', 'Half Time/Full Time - Draw/Away'), ('htft_ah', 'Half Time/Full Time - Away/Home'), ('htft_ad', 'Half Time/Full Time - Away/Draw'), ('htft_aa', 'Half Time/Full Time - Away/Away'), ('ah_home_minus_05', 'Asian Handicap Home -0.5'), ('ah_away_plus_05', 'Asian Handicap Away +0.5'), ('ah_home_minus_1', 'Asian Handicap Home -1'), ('ah_away_plus_1', 'Asian Handicap Away +1'), ('cs_1_0', 'Correct Score 1-0'), ('cs_2_0', 'Correct Score 2-0'), ('cs_2_1', 'Correct Score 2-1'), ('cs_0_0', 'Correct Score 0-0'), ('cs_1_1', 'Correct Score 1-1'), ('cs_0_1', 'Correct Score 0-1'), ('cs_0_2', 'Correct Score 0-2'), ('cs_1_2', 'Correct Score 1-2'), ('ht_home', 'Half Time - Home Win'), ('ht_draw', 'Half Time - Draw'), ('ht_away', 'Half Time - Away Win'), ('odd', 'Total Goals Odd'), ('even', 'Total Goals Even'), ('dnb_home', 'Draw No Bet - Home'), ('dnb_away', 'Draw No Bet - Away'), ('win_to_nil_home', 'Home Win to Nil'), ('win_to_nil_away', 'Away Win to Nil'), ('ht_1x', 'Half Time Double Chance 1X'), ('ht_12', 'Half Time Double Chance 12'), ('ht_x2', 'Half Time Double Chance X2'), ('btts_win_home', 'BTTS & Home Win'), ('btts_win_away', 'BTTS & Away Win'), ('home_over_1_5', 'Home Team Over 1.5 Goals'), ('home_under_1_5', 'Home Team Under 1.5 Goals'), ('away_over_1_5', 'Away Team Over 1.5 Goals'), ('away_under_1_5', 'Away Team Under 1.5 Goals')], max_length=30),
        ),
        migrations.AlterField(
            model_name='expressbetselection',
            name='bet_type',
            field=models.CharField(max_length=30),
        ),
    ]
