# Generated by Django 5.2.8 on 2026-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_bet_options_alter_expressbet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='upcoming', max_length=20),
        ),
    ]
