# Generated by Django 5.2.8 on 2026-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_minute',
            field=models.CharField(blank=True, help_text="Current minute for live matches (e.g., '45', 'HT')", max_length=10, null=True),
        ),
    ]
