# Generated by Django 5.2.8 on 2026-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_alter_bet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10),
        ),
    ]
