# Generated by Django 5.2.8 on 2026-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_alter_bet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
