# Generated by Django 5.2.8 on 2026-02-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_match_league_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='correct_score_grid',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
