# Generated by Django 5.2.8 on 2026-02-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_match_correct_score_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='correct_score_grid',
        ),
        migrations.AddField(
            model_name='odds',
            name='correct_score_grid',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
