# Generated by Django 5.2.8 on 2026-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_remove_match_correct_score_grid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_minute',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
