# Generated by Django 5.2.8 on 2026-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_match_match_minute_match_match_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league_priority',
            field=models.IntegerField(default=0),
        ),
    ]
