# Generated by Django 5.2.8 on 2026-02-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_match_league_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='league_priority',
        ),
        migrations.AddField(
            model_name='match',
            name='league_order',
            field=models.IntegerField(default=99999),
        ),
    ]
