# Generated by Django 5.2.8 on 2026-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField(blank=True, default='')),
                ('live_matches_log', models.TextField(blank=True, default='')),
                ('upcoming_matches_log', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Combined Scraper Status',
            },
        ),
    ]
