# Generated by Django 5.2.8 on 2026-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_module', '0002_combinedscraperstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Live Scraper Status',
            },
        ),
        migrations.AddField(
            model_name='combinedscraperstatus',
            name='live_scraper_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combinedscraperstatus',
            name='main_scraper_running',
            field=models.BooleanField(default=False),
        ),
    ]
